# Generated by Django 4.0.4 on 2022-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_task',
            field=models.CharField(choices=[('CONCLUIDO', 'Concluido'), ('AGENDADO', 'Agendado')], default='AGENDADO', max_length=250),
        ),
    ]
